"""empty message

Revision ID: 40f3fda60952
Revises: 
Create Date: 2025-11-25 21:03:26.262794

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '40f3fda60952'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contratos', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=mysql.ENUM('activo', 'cancelado', 'finalizado', 'rescindido', 'inactivo'),
               nullable=False)

    with op.batch_alter_table('cuotas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cuotas', schema=None) as batch_op:
        batch_op.drop_column('tipo')

    with op.batch_alter_table('contratos', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=mysql.ENUM('activo', 'cancelado', 'finalizado', 'rescindido', 'inactivo'),
               nullable=True)

    # ### end Alembic commands ###
